runtime: custom
env: flex
manual_scaling:
  instances: 1
resources:
  cpu: 2
  memory_gb: 8
  disk_size_gb: 30
network:
  name: ghost-vpc
  subnetwork_name: us-central1
  instance_ip_mode: internal
  forwarded_ports:
